name: Release Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}