name: Release Automation

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Use Docker to run Semantic Release
                    
      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
