name: Release Automation

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Grant execute permission to the script
      - name: Make script executable
        run: chmod +x semantic-release.sh

      - name: Run Semantic Release Script
        run: ./semantic-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}