name: Release Automation

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: Env-Variables
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          export GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: NPM Install
        run: |
          npm i
          npm i -g semantic-release    

      - name: Create Release
        run: |
          semantic-release
