name: Release Automation

on:
  push:
    branches:
      - main
      - test

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
